import { Book } from '../models/book'; 

export const mockBooks: Book[] = [
  {
    id: 'b2',
    img: 'book-images/fund_fisica_1.jpg',
    titulo: 'Fundamentos da Física - Vol 1: Mecânica',
    descricao: 'Referência no ensino de física. Aborda cinemática, dinâmica e estática com clareza, sendo ideal para a consolidação da base teórica.',
    autor: 'Ramalho, Nicolau e Toledo',
    categoria: 'Livro Didático',
    idioma: 'Português',
    nivel: 'Intermediário',
    preco: 185.00,
    tags: ['Física', 'Mecânica', 'Vestibular'],
    isPremium: false,
    discount: 15,
    compravel: true
  },
  {
    id: 'b4',
    img: 'book-images/the_black_box.jpg',
    titulo: 'A Sociedade das Caixas Pretas',
    descricao: 'Obra essencial para entender como algoritmos secretos controlam a informação, o dinheiro e impactam a sociedade através de discriminação algorítmica.',
    autor: 'Frank Pasquale',
    categoria: 'Ciências Humanas',
    idioma: 'Português',
    nivel: 'Pesquisa / Graduação',
    preco: 75.00,
    tags: ['Tecnologia', 'Ética', 'Sociedade'],
    isPremium: false,
    discount: null,
    compravel: false
  },
  {
    id: 'b5',
    img: 'book-images/sociedade do cansaco.jpg',
    titulo: 'Sociedade do Cansaço',
    descricao: 'Uma análise filosófica sobre as doenças neuronais do século XXI, como depressão e burnout, causadas pela cobrança excessiva por desempenho.',
    autor: 'Byung-Chul Han',
    categoria: 'Filosofia',
    idioma: 'Português',
    nivel: 'Ensino Superior',
    preco: 45.00,
    tags: ['Filosofia', 'Sociologia', 'Humanas'],
    isPremium: true,
    discount: null,
    compravel: true
  },
  {
    id: 'b7',
    img: 'book-images/inteligencia artificial.jpg',
    titulo: 'Inteligência Artificial',
    descricao: 'Discussão profunda sobre como tecnologias de reconhecimento facial perpetuam a discriminação algorítmica no contexto brasileiro e a necessidade de uma tecnologia mais ética.',
    autor: 'Nina da Hora',
    categoria: 'Artigo Científico',
    idioma: 'Português',
    nivel: 'Pesquisa / Graduação',
    preco: 0.00,
    tags: ['Tecnologia', 'Ética', 'Inteligência Artificial'],
    isPremium: false,
    discount: null,
    compravel: false
  },
  {
    id: 'b8',
    img: 'book-images/topicos_de_fisica_2.jpg',
    titulo: 'Tópicos de Física - Vol 2: Termologia e Ondulatória',
    descricao: 'Excelente material de transição para quem já concluiu cinemática e dinâmica e precisa avançar para calorimetria e termodinâmica visando vestibulares militares de altíssimo nível.',
    autor: 'Gualter, Newton e Helou',
    categoria: 'Apostila',
    idioma: 'Português',
    nivel: 'Avançado',
    preco: 0.00,
    tags: ['Física', 'Termodinâmica', 'Calorimetria', 'Militar'],
    isPremium: false,
    discount: null,
    compravel: false
  },
  {
    id: 'b9',
    img: 'book-images/linalgebra.jpg',
    titulo: 'Álgebra Linear e Suas Aplicações',
    descricao: 'Material essencial para a base de ciências exatas, cobrindo vetores, matrizes, transformações lineares e aplicações práticas na engenharia de computação.',
    autor: 'Gilbert Strang',
    categoria: 'Livro Didático',
    idioma: 'Português',
    nivel: 'Ensino Superior',
    preco: 0.00,
    tags: ['Matemática', 'Álgebra Linear', 'Engenharia'],
    isPremium: false,
    discount: null,
    compravel: true
  },
];

export const mockPremiumBooks: Book[] = [
  {
    id: 'b3',
    img: 'book-images/guidorizzi.jpg',
    titulo: 'Um Curso de Cálculo - Vol. 1',
    descricao: 'O livro de cálculo mais tradicional nas engenharias e cursos de exatas do Brasil. Focado em limites, derivadas e introdução a integrais.',
    autor: 'Hamilton Luiz Guidorizzi',
    categoria: 'Livro Técnico',
    idioma: 'Português',
    nivel: 'Ensino Superior',
    preco: 195.00,
    tags: ['Cálculo', 'Matemática', 'Engenharia'],
    isPremium: true,
    discount: 10,
    compravel: true
  },
  {
    id: 'b6',
    img: '/book-images/clean_code.jpg',
    titulo: 'Código Limpo (Clean Code)',
    descricao: 'Habilidades práticas de software ágil. Aprenda a ler, escrever e refatorar códigos para torná-los robustos e manuteníveis no longo prazo.',
    autor: 'Robert C. Martin',
    categoria: 'Livro Técnico',
    idioma: 'Português',
    nivel: 'Intermediário',
    preco: 110.00,
    tags: ['Computação', 'Programação', 'Engenharia'],
    isPremium: true,
    discount: 20,
    compravel: true
  },
  {
    id: 'b1',
    img: 'book-images/fme_9.jpg',
    titulo: 'Fundamentos da Matemática Elementar - Vol 9: Geometria Plana',
    descricao: 'Obra clássica e indispensável para aprofundamento em geometria, cobrindo teoria completa, demonstrações e uma vasta gama de exercícios de vestibulares.',
    autor: 'Osvaldo Dolce e José Nicolau Pompeo',
    categoria: 'Livro Didático',
    idioma: 'Português',
    nivel: 'Avançado',
    preco: 140.00,
    tags: ['Matemática', 'Geometria', 'Vestibular'],
    isPremium: false,
    discount: null,
    compravel: false
  }
]